apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: wf-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wf-sa
subjects:
- kind: ServiceAccount
  name: wf-sa
  namespace: default