apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: wf-sa
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - secrets
  - persistentvolumes
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'