apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello

  templates:
  - name: hello
    dag:
      tasks:
      - name: A
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello1"}]
      - name: B
        dependencies: [A]
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello2a"}]
      - name: C
        dependencies: [A]
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello2b"}]
      - name: D
        dependencies: [B, C]
        template: whalesay
        arguments:
          parameters:  [{name: message, value: "hello3"}]

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
